import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/Components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
// title name
export const metadata = {
  title: "Next Hero App",
  description: "Generated by create next app",
};
// main layout of website
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        <div className="h-screen">

          {children}
        </div>
        <footer className="text-center">
          footer is here
        </footer>

      </body>
    </html>
  );
}
